// server/src/config/constants.js
export const ROLES = {
  CITIZEN: 'citizen',
  OFFICER: 'officer',
  MANAGER: 'manager',
  ADMIN: 'admin'
};

export const COMPLAINT_STATUS = {
  SUBMITTED: 'Submitted',
  UNDER_REVIEW: 'Under Review',
  ASSIGNED: 'Assigned',
  IN_PROGRESS: 'In Progress',
  RESOLVED: 'Resolved',
  AWAITING_CONFIRMATION: 'Awaiting Citizen Confirmation',
  CLOSED: 'Closed',
  REOPENED: 'Reopened'
};

export const COMPLAINT_PRIORITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical'
};

export const SLA_HOURS = {
  Low: 168,      // 7 days
  Medium: 120,   // 5 days
  High: 72,      // 3 days
  Critical: 24   // 24 hours
};

export const NOTIFICATION_TYPES = {
  COMPLAINT_CREATED: 'COMPLAINT_CREATED',
  STATUS_UPDATED: 'STATUS_UPDATED',
  COMPLAINT_ASSIGNED: 'COMPLAINT_ASSIGNED',
  COMPLAINT_ESCALATED: 'COMPLAINT_ESCALATED',
  COMPLAINT_RESOLVED: 'COMPLAINT_RESOLVED',
  COMPLAINT_REOPENED: 'COMPLAINT_REOPENED',
  RESOLUTION_CONFIRMED: 'RESOLUTION_CONFIRMED',
  SLA_OVERDUE: 'SLA_OVERDUE',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

export const AUDIT_ACTIONS = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_UPDATE: 'USER_UPDATE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',
  COMPLAINT_CREATE: 'COMPLAINT_CREATE',
  COMPLAINT_UPDATE: 'COMPLAINT_UPDATE',
  COMPLAINT_STATUS_CHANGE: 'COMPLAINT_STATUS_CHANGE',
  COMPLAINT_ASSIGN: 'COMPLAINT_ASSIGN',
  COMPLAINT_REASSIGN: 'COMPLAINT_REASSIGN',
  COMPLAINT_RESOLVE: 'COMPLAINT_RESOLVE',
  COMPLAINT_REOPEN: 'COMPLAINT_REOPEN',
  COMPLAINT_CONFIRM: 'COMPLAINT_CONFIRM',
  COMPLAINT_FEEDBACK: 'COMPLAINT_FEEDBACK',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  SYSTEM_SETTING_UPDATE: 'SYSTEM_SETTING_UPDATE'
};

export const AUDIT_RESULTS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  DENIED: 'DENIED'
};

export const SECURITY_EVENT_TYPES = {
  FAILED_LOGIN: 'FAILED_LOGIN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SUSPICIOUS_PAYLOAD: 'SUSPICIOUS_PAYLOAD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
};
